flowchart TD
    A[Usuarios Web] --> B[Frontend React y Tailwind]
    B --> C[Backend FastAPI]
    C --> D[MySQL]
    C --> E[API externa de correo]
    C --> F[API externa de archivos]
    G[Candidatos desde portal publico] --> B
